version: '3.8'

services:
  tomcat:
    image: tomcat:10.1.30
    container_name: tomcat
    volumes:
      - ./servlet/target/servlet-1.0-SNAPSHOT.war:/usr/local/tomcat/webapps/servlet.war
      - ./server.xml:/usr/local/tomcat/conf/server.xml
      - ./server.jks:/usr/local/tomcat/conf/server.jks
      - ./trusted.jks:/usr/local/tomcat/conf/trusted.jks
    environment:
      - CATALINA_OPTS=-Dcom.sun.security.enableCRLDP=true
    command: ["catalina.sh", "run"]
  client:
    image: eclipse-temurin:21
    container_name: client
    environment:
      - CLASSPATH=/opt/app/*:/opt/app/dependency/*
    volumes:
      - ./app/target:/opt/app
    tty: true
  ca:
    image: eclipse-temurin:21
    container_name: ca
    environment:
      - CLASSPATH=/opt/app/*:/opt/app/dependency/*
    volumes:
      - ./app/target:/opt/app
    tty: true
  proxy:
    image: eclipse-temurin:21
    container_name: proxy
    environment:
      - CLASSPATH=/opt/app/*:/opt/app/dependency/*
    volumes:
      - ./app/target:/opt/app
    tty: true
